---
- name: Install all containers
  hosts: "*"
  become: yes

  ## config from this link: https://github.com/christianlempa/videos/tree/main/ansible-and-docker
  tasks:
    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy Wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        networks:
          - name: wordpress
        ports:
          - "80:80"
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "bapasqui"
          WORDPRESS_DB_PASSWORD: "pass"
          WORDPRESS_DB_NAME: "exampledb"
          WORDPRESS_HOME: "http://192.168.56.110/wordpress"
          WORDPRESS_SITEURL: "http://192.168.56.110/wordpress"
        restart_policy: always

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          - name: wordpress
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "exampledb"
          MYSQL_USER: "bapasqui"
          MYSQL_PASSWORD: "pass"
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        restart_policy: always

    - name: Deploy PhpMyAdmin
      community.docker.docker_container:
        name: phpmyadmin
        image: phpmyadmin:latest
        ports:
          - "8081:80"
          - "8082:8080"
        networks:
          - name: wordpress
        volumes:
          - phpmyadmin:/var/www/html
        env:
          PMA_HOST: "db"
          MYSQL_ROOT_PASSWORD: "pass"
        restart_policy: always

    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        networks:
          - name: wordpress
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - portainer:/data
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always

    # - name : Deploy Caddy
    #   community.docker.docker_container:
    #     name: caddy
    #     image: caddy:latest
    #     ports:
    #       - "80:80"
    #     networks:
    #       - name: wordpress
    #     volumes:
    #       - caddy:/etc/caddy
    #       - caddy_data:/data
    #       - caddy_config:/config
    #     restart_policy: always
  
