---
- name: Install all containers
  hosts: "*"
  become: yes

  ## config from this link: https://github.com/christianlempa/videos/tree/main/ansible-and-docker
  tasks:
    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy Duckdns
      community.docker.docker_container:
        name: duckdns
        image: linuxserver/duckdns:latest
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/Paris"
          SUBDOMAINS: "bapasqui-cloud1"
          TOKEN: ""
        restart_policy: always

    - name: Deploy Wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        networks:
          - name: wordpress
        expose:
          - "80"
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "bapasqui"
          WORDPRESS_DB_PASSWORD: "pass"
          WORDPRESS_DB_NAME: "exampledb"
        restart_policy: always

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          - name: wordpress
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "exampledb"
          MYSQL_USER: "bapasqui"
          MYSQL_PASSWORD: "pass"
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        restart_policy: always

    - name: Deploy PhpMyAdmin
      community.docker.docker_container:
        name: phpmyadmin
        image: phpmyadmin:latest
        expose:
          - "80"
        networks:
          - name: wordpress
        volumes:
          - phpmyadmin:/var/www/html
        env:
          PMA_HOST: "db"
          MYSQL_ROOT_PASSWORD: "pass"
        restart_policy: always

    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        networks:
          - name: wordpress
        expose:
          - "9000"
        ports:
          - "8000:8000"
        volumes:
          - portainer:/data
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always

    - name : Copy files to server
      copy:
        src: Caddyfile
        dest: ~/Caddyfile


    - name: Deploy Caddy
      community.docker.docker_container:
        name: caddy
        image: caddy:latest
        networks:
          - name: wordpress
        ports:
          - "443:443"
          - "80:80"
        volumes:
          - caddy:/etc/caddy
          - caddy_data:/data
          - caddy_config:/config
          - /var/run/docker.sock:/var/run/docker.sock
          - ~/Caddyfile:/etc/caddy/Caddyfile
        restart_policy: always
  
