---
- name: Reset all containers
  hosts: "*"
  become: yes

  tasks:
    - name: Stop all containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - wordpress
        - db
        - phpmyadmin
        - portainer
        - duckdns
        - caddy

    - name: Remove all containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - wordpress
        - db
        - phpmyadmin
        - portainer
        - duckdns
        - caddy

    - name: Remove all networks
      community.docker.docker_network:
        name: "{{ item }}"
        state: absent
      with_items:
        - wordpress

    - name: Remove all volumes
      community.docker.docker_volume:
        name: "{{ item }}"
        state: absent
      with_items:
        - wordpress
        - db
        - phpmyadmin
        - portainer
        - duckdns
        - caddy

    - name : Remove all images
      community.docker.docker_image:
        name: "{{ item }}"
        state: absent
      with_items:
        - wordpress
        - mysql
        - phpmyadmin
        - portainer
        - caddy

    - name: Remove Docker Compose folder
      become: yes
      file:
        path: ~/cloud-1
        state: absent
    



