---
- name: Setup hosts
  hosts: "*"
  become: yes
  vars_files:
    - ../vault.yml

  tasks:
    - name: Update & Upgrade Packages
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: Check if folder for Docker Compose exists
      stat: path=~/cloud-1
      register: cloud1_dir

    - name: Check if .env file exists
      stat: path=~/cloud-1/.env
      register: env_file

    - name: Check if docker-compose file exists
      stat: path=~/cloud-1/docker-compose.yml
      register: docker_compose_file

    - name: Create folder for Docker Compose
      file:
        path: ~/cloud-1
        state: directory
        mode: '0755'
      when: cloud1_dir.stat.exists == False 

    - name: Create .env file for Docker Compose
      template:
        src: ../config/env.j2
        dest: ~/cloud-1/.env
        mode: '0600'
      when: env_file.stat.exists == False

    - name: Copy Docker Compose file
      copy:
        src: ../config/docker-compose.yml
        dest: ~/cloud-1/docker-compose.yml
        mode: '0600'
      when: docker_compose_file.stat.exists == False