---
- name: Setup hosts
  hosts: "*"
  become: yes
  vars_files:
    - ../vault.yml

  tasks:
    - name: Update & Upgrade Packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Create folder for Docker Compose
      file:
        path: ~/cloud-1
        state: directory
        mode: '0755'    

    - name: Create .env file for Docker Compose
      template:
        src: ../config/env.j2
        dest: ~/cloud-1/.env
        mode: '0600'

    - name: Copy Docker Compose file
      copy:
        src: ../config/docker-compose.yml
        dest: ~/cloud-1/docker-compose.yml
        mode: '0600'

    - name: Create Caddy directory
      file: 
        path: ~/cloud-1/caddy
        state: directory
        mode: '0755'

    - name: Copy Caddyfile to server
      copy:
        src: ../config/caddy/Caddyfile
        dest: ~/cloud-1/caddy/Caddyfile
        mode: '0600'