## VARIABLES
VM_IP = "192.168.56.110"
VM_NAME = "cloud-1"

MEM = 2048
CORE = 4

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define VM_NAME do |controller|
    controller.vm.hostname = VM_NAME
    controller.vm.provider "virtualbox" do |v|
      v.memory = MEM
      v.cpus = CORE
      v.name = VM_NAME
    end
    controller.vm.network "private_network", type: "static", ip: VM_IP
    controller.vm.network "forwarded_port", guest: 80, host: 80
    controller.vm.network "forwarded_port", guest: 443, host: 443
  end
end